spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/practice
    username: postgres
    password: qwer1234
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true